[build]
  command = "pnpm install && pnpm build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "dist"
  node_bundler = "esbuild"
  
  [functions.index]
    node_bundler = "none"

